### ISSUE TITLE
Allow user to set the time zone of the excel data

### ISSUE THREAD

**Issue by Tich1212** [HydrologicEngineeringCenter/ExcelToCWMS#17]
We are currently assuming the data from excel is in UTC. 

Instead allow the user to specify that either in the db.config or the excel sheet itself.

Note: 

- Careful about daylight savings.
- If we are using a VLLOOKUPin excel, the timezone for the manual entry sheet must be the same as the import sheet.

**Comment by ktarbet** [comment]
All all time-series in the same time zone?   Perhaps the config file should have time zone  as a first/high level default.

**Comment by Tich1212** [comment]
Karl's comment from dup ticket:

"code in https://github.com/HydrologicEngineeringCenter/ExcelToCWMS/blob/main/Hec.Cwms/CwmsDatabase.cs

is hardcoded to 'UTC' in this statement

```csharp

      cmd.CommandText =
     "begin " +
     "  cwms_ts.retrieve_ts( " +
     "    :ts_cur, " +
     "    :tsid, " +
     "    :units, " +
     "    to_date(:start_time, 'dd-mon-yyyy hh24mi'), " +
     "    to_date(:end_time,   'dd-mon-yyyy hh24mi'), " +
     "    'UTC');" +
     "end;";

```

Should the time zone be an optional in the excel header:  ie.   tsid.daily....{units=cfs, time-zone=cst} ?"

**Comment by Tich1212** [comment]
Pull request #24 addressed this issue with setting the time zone in the config file.
