### ISSUE TITLE
Mask the password entry with ****

### ISSUE THREAD

**Issue by ktarbet** [HydrologicEngineeringCenter/ExcelToCWMS#3]
Mask the password entry with ****.  
move username from config file, to be manual entry
possibly cache username in local user area.

**Comment by ktarbet** [comment]
https://stackoverflow.com/questions/3404421/password-masking-console-application

**Comment by Tich1212** [comment]
Addressed with Pull Request #12
How: Created a new method GetHiddenPassword(displayMessage )that uses Console.ReadKey() and a series of if statements to swap chars with * in the console and keep track of the resulting password entered.
